package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	"github.com/typical-go/typical-rest-server/app/book/models"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

//Find func
func (r Repository) Find(id int64) (*models.Book, error) {
	arg := r.Mock.Called(id)

	var book *models.Book
	if result, ok := arg.Get(0).(func(int64) *models.Book); ok {
		book = result(id)
	} else {
		if arg.Get(0) != nil {
			book, _ = arg.Get(0).(*models.Book)
		}
	}

	var err error
	if result, ok := arg.Get(1).(func(int64) error); ok {
		err = result(id)
	} else {
		err = arg.Error(1)
	}

	return book, err
}

//List func
func (r Repository) List() ([]*models.Book, error) {
	arg := r.Mock.Called()

	var book []*models.Book
	if result, ok := arg.Get(0).([]*models.Book); ok {
		book = result
	} else {
		if arg.Get(0) != nil {
			book, _ = arg.Get(0).([]*models.Book)
		}
	}

	var err error
	if result, ok := arg.Get(1).(error); ok {
		err = result
	} else {
		err = arg.Error(1)
	}

	return book, err
}

//Insert func
func (r Repository) Insert(ctx context.Context, book interface{}) (int64, error) {
	bookParse, _ := book.(*models.Book)
	arg := r.Mock.Called(ctx, bookParse)

	var lastInsertID int64
	if result, ok := arg.Get(0).(func(context.Context, *models.Book) int64); ok {
		lastInsertID = result(ctx, bookParse)
	} else {
		lastInsertID = arg.Get(0).(int64)
	}

	var err error
	if result, ok := arg.Get(1).(func(context.Context, *models.Book) error); ok {
		err = result(ctx, bookParse)
	} else {
		err = arg.Error(1)
	}

	return lastInsertID, err
}

//Update func
func (r Repository) Update(ctx context.Context, book interface{}) error {
	bookParse, _ := book.(*models.Book)
	arg := r.Mock.Called(ctx, bookParse)

	var err error
	if result, ok := arg.Get(0).(func(context.Context, *models.Book) error); ok {
		err = result(ctx, bookParse)
	} else {
		err = arg.Error(0)
	}

	return err
}

//Delete func
func (r Repository) Delete(ctx context.Context, id int64) error {
	arg := r.Mock.Called(ctx, id)

	var err error
	if result, ok := arg.Get(0).(func(context.Context, int64) error); ok {
		err = result(ctx, id)
	} else {
		err = arg.Error(0)
	}

	return err
}
